version: '2'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "${PWD}:/home/node"

    links:
      - couchdb:COUCHDB
      - db:DB

  couchdb:
    image: couchdb:1.6.1
    ports:
      - "5984:5984"

  db:
    image: mariadb:10.1.20
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - "${PWD}/db:/var/${MYSQL_DATABASE}"
