-- MySQL Script generated by MySQL Workbench
-- Thu Jan  5 13:08:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema boilerplate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boilerplate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boilerplate` DEFAULT CHARACTER SET utf8 ;
USE `boilerplate` ;

-- -----------------------------------------------------
-- Table `boilerplate`.`ACL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boilerplate`.`ACL` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(512) NULL DEFAULT NULL,
  `property` VARCHAR(512) NULL DEFAULT NULL,
  `accessType` VARCHAR(512) NULL DEFAULT NULL,
  `permission` VARCHAR(512) NULL DEFAULT NULL,
  `principalType` VARCHAR(512) NULL DEFAULT NULL,
  `principalId` VARCHAR(512) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boilerplate`.`AccessToken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boilerplate`.`AccessToken` (
  `id` VARCHAR(255) NOT NULL,
  `ttl` INT(11) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `userId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boilerplate`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boilerplate`.`Role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(512) NOT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `created` TEXT NULL DEFAULT NULL,
  `modified` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boilerplate`.`RoleMapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boilerplate`.`RoleMapping` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `principalType` VARCHAR(512) NULL DEFAULT NULL,
  `principalId` VARCHAR(512) NULL DEFAULT NULL,
  `roleId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `principalId` (`principalId`(255) ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boilerplate`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boilerplate`.`User` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `realm` VARCHAR(512) NULL DEFAULT NULL,
  `username` VARCHAR(512) NULL DEFAULT NULL,
  `password` VARCHAR(512) NOT NULL,
  `email` VARCHAR(512) NOT NULL,
  `emailVerified` TINYINT(1) NULL DEFAULT NULL,
  `verificationToken` VARCHAR(512) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boilerplate`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boilerplate`.`project` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boilerplate`.`app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boilerplate`.`app` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_id` INT(11) NOT NULL,
  `name` VARCHAR(120) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_app_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_app_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `boilerplate`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boilerplate`.`schema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boilerplate`.`schema` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NULL DEFAULT NULL,
  `schema` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boilerplate`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boilerplate`.`document` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `schema_id` INT(11) NOT NULL,
  `app_id` INT(11) NULL DEFAULT NULL,
  `document_id` INT(11) NULL DEFAULT NULL,
  `name_id` VARCHAR(45) NULL,
  `tags` VARCHAR(256) NULL DEFAULT NULL,
  `publish` INT(11) NULL DEFAULT NULL,
  `ranking` INT(11) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `body` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_document_document1_idx` (`document_id` ASC),
  INDEX `fk_document_app1_idx` (`app_id` ASC),
  INDEX `fk_document_schema1_idx` (`schema_id` ASC),
  CONSTRAINT `fk_document_app1`
    FOREIGN KEY (`app_id`)
    REFERENCES `boilerplate`.`app` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `boilerplate`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_schema1`
    FOREIGN KEY (`schema_id`)
    REFERENCES `boilerplate`.`schema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boilerplate`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boilerplate`.`language` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `boilerplate`.`document_translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boilerplate`.`document_translation` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `document_id` INT(11) NOT NULL,
  `language_id` INT(11) NOT NULL,
  `body` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_document_translation_document1_idx` (`document_id` ASC),
  INDEX `fk_document_translation_language1_idx` (`language_id` ASC),
  CONSTRAINT `fk_document_translation_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `boilerplate`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_translation_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `boilerplate`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
